USE ROLE ENT_ENGAGE_OWNER_{{ENVR}}_ROLE;
USE DATABASE ENT_STG_ENGAGE_{{DB_SUFFIX}};
USE SCHEMA LOAD_STG;

CREATE OR REPLACE EXTERNAL TABLE LOAD_STG.BTP_CVD_MD_DS_FIXED_ASSET_INCR_EXT 
(    MANDT  VARCHAR AS (NULLIF(($1:MANDT::VARCHAR),'')),
     ASSET_ID  VARCHAR AS (NULLIF(($1:ASSET_ID::VARCHAR),'')),
     PROJECT_WBS_CODE  VARCHAR AS (NULLIF(($1:PROJECT_WBS_CODE::VARCHAR),'')),
     DATE_IN_SERVICE  DATE AS ($1:DATE_IN_SERVICE::DATE),
     LIFE_IN_MONTHS  VARCHAR AS (NULLIF(($1:LIFE_IN_MONTHS::VARCHAR),'')),
     DEP_GL_ACCOUNT  VARCHAR AS (NULLIF(($1:DEP_GL_ACCOUNT::VARCHAR),'')),
	 DEP_COMPANY_CODE  VARCHAR AS (NULLIF(($1:DEP_COMPANY_CODE::VARCHAR),'')),
     DEP_COST_CENTER  VARCHAR AS (NULLIF(($1:DEP_COST_CENTER::VARCHAR),'')),
     ASSET_CATEGORY_SHORT_TEXT  VARCHAR AS (NULLIF(($1:ASSET_CATEGORY_SHORT_TEXT::VARCHAR),'')),
     ASSET_CATEGORY_LONG_TEXT  VARCHAR AS (NULLIF(($1:ASSET_CATEGORY_LONG_TEXT::VARCHAR),'')),
     RETIREMENT_DATE  DATE AS ($1:RETIREMENT_DATE::DATE),
     ASSET_DESC  VARCHAR AS (NULLIF(($1:ASSET_DESC::VARCHAR),'')),
	 ORIGINAL_COST  NUMBER(23, 2) AS ($1:ORIGINAL_COST::NUMBER(23, 2)), 
     CURRENCY_CODE VARCHAR AS (NULLIF(($1:CURRENCY_CODE::VARCHAR),'')),
     UPDATE_DATE  TIMESTAMP AS ($1:UPDATE_DATE::TIMESTAMP),
     topic_partition  NUMBER(38, 0) AS ($1:topic_partition::NUMBER(38, 0)),
     offset  NUMBER(38, 0) AS ($1:offset::NUMBER(38, 0)),
     topic_record_timestamp  TIMESTAMP AS ($1:topic_record_timestamp::TIMESTAMP), 
     LOAD_DATE TIMESTAMP_NTZ(9) AS (TO_TIMESTAMP 
           (
             SPLIT_PART(SPLIT_PART(METADATA$FILENAME, '/', 5), '=', 2) ||
             SPLIT_PART(SPLIT_PART(METADATA$FILENAME, '/', 6), '=', 2),
             'YYYY-MM-DDHH'
           ))
)
PARTITION BY (LOAD_DATE) 
LOCATION = @STG_ENGAGE/btp/incr/formatted/fct-btphana.cvd-md-ds-fixed-asset/
FILE_FORMAT = FF.PARQUET_FORMAT 
; 